"""empty message

Revision ID: 85339054ed82
Revises: 329796b2c6dd
Create Date: 2022-05-20 00:41:36.045527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85339054ed82'
down_revision = '329796b2c6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
